const getUsersRoutes = (permissions) => {
  const permissionRequired = (permission) => {
    return true;
  };
  return [
    {
      type: "title",
      name: "Kikits",
      title: "Kikits",
      key: "title",
      route: "/",
      component: "Dashboard",
    },
    { type: "divider", key: "divider-0" },
    {
      type: "hidden",
      name: "Profile",
      key: "profile",
      icon: "user",
      route: "/profile",
      component: "Profile",
    },
    {
      type: "hidden",
      name: "Organization",
      key: "organization",
      route: "/organization/*",
      component: "Organization",
    },
    permissionRequired("events.read") && {
      name: "Event",
      key: "event",
      route: "/events/:id/*",
      component: "Event",
      type: "hidden",
    },
    permissionRequired("events.read") && {
      type: "item",
      name: "Events",
      key: "events",
      route: "/events",
      component: "Events",
      icon: "theater_comedy",
    },
    permissionRequired("members.read") && {
      name: "Member",
      key: "member",
      route: "/members/:id/*",
      component: "Member",
      type: "hidden",
    },
    permissionRequired("members.read") && {
      type: "item",
      name: "Members",
      key: "members",
      route: "/members",
      icon: "people",
      component: "Members",
    },
    permissionRequired("orders.read") && {
      name: "Order",
      key: "Order",
      route: "/orders/:id/*",
      component: "Order",
      type: "hidden",
    },
    permissionRequired("orders.read") && {
      type: "item",
      name: "Orders",
      icon: "shopping_cart",
      key: "orders",
      route: "/orders",
      component: "Orders",
    },
    permissionRequired("tickets.read") && {
      name: "Ticket",
      key: "ticket",
      route: "/tickets/:id",
      component: "Ticket",
      type: "hidden",
    },
    permissionRequired("tickets.read") && {
      type: "item",
      name: "Find Tickets",
      icon: "search",
      key: "tickets",
      route: "/tickets",
      component: "Tickets",
    },
    {
      type: "item",
      name: "Media Gallery",
      key: "media-gallery",
      icon: "photo",
      route: "/media-gallery",
      component: "MediaGallery",
    },
    permissionRequired("events.read") && {
      type: "collapse",
      name: "Codes & Scanners",
      key: "codes-and-scanners",
      icon: "qr_code",
      collapse: [
        permissionRequired("accessCodes.read") && {
          type: "item",
          name: "Access Codes",
          key: "access-codes",
          route: "/access-codes",
          component: "AccessCodes",
        },
        permissionRequired("accessCodes.read") && {
          type: "hidden",
          name: "Access Code",
          key: "access-code",
          route: "/access-codes/:id",
          component: "AccessCode",
        },
        permissionRequired("facts.read") && {
          name: "Fact",
          key: "fact",
          route: "/facts/:id",
          component: "Fact",
          type: "hidden",
        },
        permissionRequired("facts.read") && {
          type: "item",
          name: "Facts",
          key: "facts",
          route: "/facts",
          component: "Facts",
        },
        permissionRequired("qrcodes.read") && {
          name: "QR Code",
          key: "qr-code",
          route: "/qrcodes/:id/*",
          component: "QRCode",
          type: "hidden",
        },
        permissionRequired("qrcodes.read") && {
          type: "item",
          name: "QR Codes",
          key: "qrcodes",
          route: "/qrcodes",
          component: "QRCodes",
        },
        permissionRequired("tickets.read") && {
          type: "item",
          name: "Scanner",
          key: "scanner",
          route: "/tickets/scanner",
          component: "Scanner",
        },
        permissionRequired("scanner.read") && {
          name: "Scanner Role",
          key: "scanner-role",
          route: "/scanner-roles/:id",
          component: "ScannerRole",
          type: "hidden",
        },
        permissionRequired("scanner.read") && {
          type: "item",
          name: "Scanner Roles",
          key: "scanner-roles",
          route: "/scanner-roles",
          component: "ScannerRoles",
        },
        permissionRequired("scanner.read") && {
          name: "Scanner Action",
          key: "scanner-action",
          route: "/scanner-actions/:id",
          component: "ScannerAction",
          type: "hidden",
        },
        permissionRequired("scanner.read") && {
          type: "item",
          name: "Scanner Actions",
          key: "scanner-actions",
          route: "/scanner-actions",
          component: "ScannerActions",
        },
      ].filter(Boolean),
    },
    // {
    //   type: "collapse",
    //   name: "Reports",
    //   key: "reports",
    //   icon: "bar_chart",
    //   collapse: [
    //     permissionRequired("tickets.read") && {
    //       type: "hidden",
    //       name: "Charge",
    //       key: "charge",
    //       route: "/charges/:id",
    //       component: "Charge",
    //     },
    //     permissionRequired("tickets.read") && {
    //       type: "item",
    //       name: "Charges",
    //       key: "charges",
    //       route: "/charges",
    //       component: "Charges",
    //     },
    //     permissionRequired("tickets.read") && {
    //       name: "Cart",
    //       key: "cart",
    //       route: "/carts/:id",
    //       component: "Cart",
    //       type: "hidden",
    //     },
    //     permissionRequired("tickets.read") && {
    //       type: "item",
    //       name: "Carts",
    //       key: "carts",
    //       route: "/carts",
    //       component: "Carts",
    //     },
    //   ].filter(Boolean),
    // },
    permissionRequired("news.read") && {
      type: "collapse",
      name: "Website & Content",
      key: "website-and-content",
      icon: "newspaper",
      collapse: [
        // permissionRequired("authors.read") && {
        //   name: "Author",
        //   key: "author",
        //   route: "/authors/:id",
        //   component: "Author",
        //   type: "hidden",
        // },
        // permissionRequired("authors.read") && {
        //   type: "item",
        //   name: "Authors",
        //   key: "authors",
        //   route: "/authors",
        //   component: "Authors",
        // },
        // {
        //   type: "item",
        //   name: "Content Types",
        //   key: "content-types",
        //   route: "/content-types",
        //   component: "ContentTypes",
        // },
        // {
        //   name: "Content Type",
        //   key: "content-type",
        //   route: "/content-types/:id/*",
        //   component: "ContentType",
        //   type: "hidden",
        // },
        // {
        //   type: "item",
        //   name: "Content",
        //   key: "content",
        //   route: "/content/:id",
        //   component: "Content",
        //   type: "hidden",
        // },
        // {
        //   type: "item",
        //   name: "Content",
        //   key: "content",
        //   route: "/content/create/:contentTypeId",
        //   component: "Content",
        //   type: "hidden",
        // },
        permissionRequired("locations.read") && {
          name: "Location",
          key: "location",
          route: "/locations/:id/*",
          component: "Location",
          type: "hidden",
        },
        permissionRequired("locations.read") && {
          type: "item",
          name: "Locations",
          key: "locations",
          route: "/locations",
          component: "Locations",
        },
        // permissionRequired("news.read") && {
        //   name: "News",
        //   key: "news-article",
        //   route: "/news/:id/*",
        //   component: "News",
        //   type: "hidden",
        // },
        // permissionRequired("news.read") && {
        //   name: "News",
        //   key: "news-generate",
        //   route: "/news/generate/*",
        //   component: "NewsGenerate",
        //   type: "hidden",
        // },
        // permissionRequired("news.read") && {
        //   type: "item",
        //   name: "News",
        //   key: "news",
        //   route: "/news",
        //   component: "NewsList",
        // },
        permissionRequired("tags.read") && {
          type: "item",
          name: "Tags",
          key: "tags",
          route: "/tags",
          component: "Tags",
        },
        permissionRequired("tags.read") && {
          name: "Tag",
          key: "tag",
          route: "/tags/:id",
          component: "Tag",
          type: "hidden",
        },
        permissionRequired("categories.read") && {
          type: "item",
          name: "Categories",
          key: "categories",
          route: "/categories",
          component: "Categories",
        },
        permissionRequired("categories.read") && {
          name: "Category",
          key: "category",
          route: "/categories/:id",
          component: "Category",
          type: "hidden",
        },
        permissionRequired("eventInvitations.read") && {
          type: "item",
          name: "Event Invitations",
          key: "eventInvitations",
          route: "/eventInvitations",
          component: "EventInvitations",
        },
        permissionRequired("eventInvitations.read") && {
          name: "Event Invitation",
          key: "eventInvitation",
          route: "/eventInvitations/:id",
          component: "EventInvitation",
          type: "hidden",
        },
      ].filter(Boolean),
    },
  ].filter(Boolean);
};

module.exports = { getUsersRoutes };
