export const DECISION_GENERATION_METHOD_LABELS: Record<string, string> = {
  MANUAL: "Created by Student",
  AI: "Generated by AI",
  FORWARDED_PREVIOUS: "Forwarded from previous",
  AI_FALLBACK: "AI Fallback",
  DEFAULTS: "Used defaults",
};

export const DECISION_GENERATION_METHOD_BADGE_CLASS: Record<string, string> = {
  MANUAL: "badge-success",
  AI: "badge-info",
  FORWARDED_PREVIOUS: "badge-muted",
  AI_FALLBACK: "badge-warning",
  DEFAULTS: "badge-warning",
};

export function getDecisionGenerationMethodLabel(
  method: string | undefined
): string {
  if (!method) return "Submitted";
  return (
    DECISION_GENERATION_METHOD_LABELS[
      method as keyof typeof DECISION_GENERATION_METHOD_LABELS
    ] ?? method
  );
}

export function getDecisionGenerationMethodBadgeClass(
  method: string | undefined
): string {
  if (!method) return "badge-success";
  return (
    DECISION_GENERATION_METHOD_BADGE_CLASS[
      method as keyof typeof DECISION_GENERATION_METHOD_BADGE_CLASS
    ] ?? "badge-success"
  );
}
