/**
 * AI Service Routes
 *
 * Provides endpoints for the AI-Powered Learning Assistant.
 * Mounted at: /v1/ai
 */
const express = require("express");
const controller = require("./ai.controller");
const router = express.Router();
const { requireAuth, requireActiveClassroom } = require("../../middleware/auth");

/**
 * @openapi
 * /v1/ai/chat:
 *   post:
 *     summary: Chat with AI assistant
 *     description: Submit a chat prompt to the classroom AI learning assistant.
 *     tags:
 *       - AI
 *     security:
 *       - BearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - message
 *             properties:
 *               message:
 *                 type: string
 *     responses:
 *       200:
 *         description: AI response returned successfully.
 */
router.post("/chat", requireAuth(), requireActiveClassroom(), controller.chat);

/**
 * @openapi
 * /v1/ai/chat/history:
 *   get:
 *     summary: Get AI chat history
 *     description: Fetch previous chat conversation log between user and AI assistant in the active classroom.
 *     tags:
 *       - AI
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200:
 *         description: Conversational message log list.
 */
router.get("/chat/history", requireAuth(), requireActiveClassroom(), controller.getChatHistory);

/**
 * @openapi
 * /v1/ai/reports:
 *   get:
 *     summary: Get classroom reports
 *     description: Returns consolidated analytics reports generated by AI for the classroom.
 *     tags:
 *       - AI
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200:
 *         description: Analytics reports.
 */
router.get("/reports", requireAuth(), requireActiveClassroom(), controller.getClassroomReports);

// Automation Task Management Endpoints
/**
 * @openapi
 * /v1/ai/automation-tasks:
 *   get:
 *     summary: Get automation tasks
 *     description: Retrieve all registered AI automation tasks for the classroom.
 *     tags:
 *       - AI Automation
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200:
 *         description: List of automation tasks.
 *   post:
 *     summary: Create automation task
 *     description: Define a new scheduled AI automation task.
 *     tags:
 *       - AI Automation
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       201:
 *         description: Task created.
 */
router.get("/automation-tasks", requireAuth(), requireActiveClassroom(), controller.getAutomationTasks);
router.post("/automation-tasks", requireAuth(), requireActiveClassroom(), controller.createAutomationTask);

/**
 * @openapi
 * /v1/ai/automation-tasks/{id}:
 *   put:
 *     summary: Update automation task
 *     description: Modify details of an AI automation task by ID.
 *     tags:
 *       - AI Automation
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - name: id
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Task updated.
 *   delete:
 *     summary: Delete automation task
 *     description: Removes an AI automation task definition.
 *     tags:
 *       - AI Automation
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - name: id
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Task deleted.
 */
router.put("/automation-tasks/:id", requireAuth(), requireActiveClassroom(), controller.updateAutomationTask);
router.delete("/automation-tasks/:id", requireAuth(), requireActiveClassroom(), controller.deleteAutomationTask);

/**
 * @openapi
 * /v1/ai/automation-tasks/runs:
 *   get:
 *     summary: Get automation task execution runs
 *     description: Fetch logs/history of AI task executions in the classroom.
 *     tags:
 *       - AI Automation
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200:
 *         description: Run records list.
 */
router.get("/automation-tasks/runs", requireAuth(), requireActiveClassroom(), controller.getAutomationTaskRuns);

module.exports = router;
